### ISSUE TITLE
extract_rets_pos_txn_from_zipline failure with backtest run in research environment

### ISSUE THREAD

**Issue by scubamut** [quantopian/pyfolio#187] opened 2015-11-01 09:50 UTC
```
from zipline import TradingAlgorithm
from zipline.api import get_datetime, get_environment, history, add_history, order_target_percent
import datetime as dt

# data is a Panel of DataFrames, one for each security
data = get_pricing(
    ['SPY'],
    start_date='2014-01-01',
    end_date = '2015-11-1',
    frequency='daily'
)

data

def initialize (context):
    
    context.symbol = symbols('SPY')
    context.i = 0
    
def handle_data (context, data) :
    
    if context.i == 0 :
        order_target_percent (context.symbol, 1)

        context.i = 1

# Create algorithm object passing in initialize and
# handle_data functions
algo_obj = TradingAlgorithm(initialize=initialize, 
                            handle_data=handle_data)

# Run algorithm
bt = algo_obj.run(data.transpose(2,1,0))

import pyfolio as pf

returns, positions, transactions, gross_lev = pf.utils.extract_rets_pos_txn_from_zipline(bt)
pf.create_full_tear_sheet(returns, positions=positions, transactions=transactions,
                          gross_lev=gross_lev)
```

results in : 

```
TypeError                                 Traceback (most recent call last)
<ipython-input-11-59eedc94e5fb> in <module>()
      1 import pyfolio as pf
----> 2 returns, positions, transactions, gross_lev = pf.utils.extract_rets_pos_txn_from_zipline(bt)
      3 pf.create_full_tear_sheet(returns, positions=positions, transactions=transactions,
      4                           gross_lev=gross_lev)

/usr/local/lib/python2.7/dist-packages/pyfolio/utils.pyc in extract_rets_pos_txn_from_zipline(backtest)
    367     transactions_frame = txn.make_transaction_frame(backtest.transactions)
    368     transactions = txn.get_txn_vol(transactions_frame)
--> 369     transactions.index = transactions.index.normalize().tz_localize('utc')
    370 
    371     return returns, positions, transactions, gross_lev

/usr/local/lib/python2.7/dist-packages/pandas/util/decorators.pyc in wrapper(*args, **kwargs)
     86                 else:
     87                     kwargs[new_arg_name] = new_arg_value
---> 88             return func(*args, **kwargs)
     89         return wrapper
     90     return _deprecate_kwarg

/usr/local/lib/python2.7/dist-packages/pandas/tseries/index.pyc in tz_localize(self, tz, ambiguous)
   1638                 new_dates = tslib.tz_convert(self.asi8, 'UTC', self.tz)
   1639             else:
-> 1640                 raise TypeError("Already tz-aware, use tz_convert to convert.")
   1641         else:
   1642             tz = tslib.maybe_get_tz(tz)

TypeError: Already tz-aware, use tz_convert to convert.

```

I could obviously work around this, but is this intentional?

**Comment by twiecki** [comment] 2015-11-01 12:46
Not intentional but a zipline version incompatibility. Thanks for reporting, we'll fix it.

**Comment by twiecki** [comment] 2015-11-01 12:47
Duplicate of https://github.com/quantopian/pyfolio/issues/187.

**Closed by twiecki** 2015-11-01 12:47 UTC
Labels: bug, help wanted, high priority
