### ISSUE TITLE
Risk Free

### ISSUE THREAD

**Issue by nossi00** [quantopian/pyfolio#648] opened 2020-06-10 12:23 UTC
Guys, how are you doing?

I'm making use of pyfolio often, and I do as many tear sheet as possible. But, I live in Brazil and I would like to use our risk free rate, but I do not know how I can input into the function "pyfolio.create_simple_tear_sheet()" 

Could someone help me out?

**Comment by eigenfoo** [comment] 2020-06-11 01:32
You might want to use `create_full_tear_sheet` instead, which takes a `benchmark_rets` argument, which can be your risk free rate.

https://github.com/quantopian/pyfolio/blob/master/pyfolio/tears.py#L55,L59

**Comment by nossi00** [comment] 2020-06-12 15:44
@eigenfoo  I tried to do that, but I got the error that I'm showing below. What can I do?





![image](https://user-images.githubusercontent.com/59965756/84520669-4e855480-acaa-11ea-9775-8decc1b0cbf6.png)

**Comment by twiecki** [comment] 2020-06-15 09:48
You need to pass in a Series with a datetimeindex. Closing as it's not a bug but feel free to ask questions.

**Closed by twiecki** 2020-06-15 09:48 UTC
